#%RAML 1.0 Trait
usage: Use this trait for pagination of result sets.
queryParameters:
  offset: 
    type: integer
    description: the offest(page number) of result set
    displayName: Offset(Page Number)
    example: 0
    required: false
  limit:
    type: integer
    description: the page size. Number of records in each page.
    displayName: Limit(Page Size)
    example: 10
    required: false
    minimum: 10
    maximum: 50
    default: 10