#%RAML 1.0 Trait

usage: Use this trait to enable partial response based on query parameters.
queryParameters: 
  fields:
    description: the fields included in response in CSV (comma separated) format.
    type: string
    required: false
    example: "firstName,lastName" 