#%RAML 1.0 Trait
usage: use this trait to search by parameter and operator. For example field can be lastName and the operator by like or equal.
queryParameters: 
  criteria:
    description: |
          fields and criteria for search JSON array [{field1,value1,operator1},{field2,value2,operator2},...,{fieldn,valuen,operatorn}] 
    example: |
      <<example>>
    required: false    
