#%RAML 1.0 Trait
usage: Use this trait for sorting the result set 
queryParameters: 
  orderBy:
    description: |
       Order the result by this fields: <<fields>> 
    type: string
    required: false
  order:
    description: order of the results which can be either descending or acsending
    enum: [desc,asc]
    default: desc
    required: false