#%RAML 1.0 DataType
properties:
  code?: 
    description: Error code. It can be the same as http code.
    examples:
      404: "404"
      500: "500"
          
  message: 
    description: 
    example: Resouce not found

          
    
    