# This workflow will build a MuleSoft project and deploy to CloudHub

name: Build and Deploy to Dev

on:
  push:
   branches: [ main ]
  workflow_dispatch:
 
   
jobs:
  build:
    runs-on: ubuntu-latest 
    
    steps:
    
    - uses: actions/checkout@v2
    
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8 
    
    
    - name: Print effective-settings (optional)
      run: mvn help:effective-settings
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Stamp artifact file name with commit hash
      run: |
        artifactName1=$(ls target/*.jar | head -1)
        commitHash=$(git rev-parse --short "$GITHUB_SHA")
        artifactName2=$(ls target/*.jar | head -1 | sed "s/.jar/-$commitHash.jar/g")
        mv $artifactName1 $artifactName2
    
    - name: Upload artifact 
      uses: actions/upload-artifact@master
      with:
          name: artifacts
          path: target/*.jar   
    
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
   

    steps:    
    
    - uses: actions/checkout@v2
    
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - uses: actions/download-artifact@master
      with:
        name: artifacts
    
    - name: Deploy to Dev
      env:
        USERNAME: ${{ secrets.anypoint_cicd_username }}
        PASSWORD: ${{ secrets.anypoint_cicd_password }}
        ENCRYPTION_KEY: ${{secrets.encryption_key }}
        ANYPOINT_PLATFORM_CLIENT_ID: ${{secrets.anypoint_platform_client_id_dev}}
        ANYPOINT_PLATFORM_CLIENT_SECRET: ${{secrets.anypoint_platform_client_secret_dev}}
        
        
      run: |
        artifactName=$(ls *.jar | head -1)
        mvn deploy -DmuleDeploy \
         -Dmule.artifact=$artifactName \
         -Danypoint.username="$USERNAME" \
         -Danypoint.password="$PASSWORD" \
         -Denv=Dev \
         -Dencryption.key="$ENCRYPTION_KEY" \
         -Danypoint.platform.client_id= "$ANYPOINT_PLATFORM_CLIENT_ID"\
         -Danypoint.platform.client_secret= "$ANYPOINT_PLATFORM_CLIENT_ID"\
         -DskipTests
         
   
